name: poli-tutor-tests

services:
  backend-tests:
    build:
      context: .
      dockerfile: docker/backend.test.Dockerfile
    volumes:
      - ./app:/app/app
      - ./rag:/app/rag
      - ./pytest.ini:/app/pytest.ini
      - ./app/coverage/backend:/app/htmlcov
