[pytest]
asyncio_mode = auto
testpaths = app/backend/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
addopts = -ra --cov=app/backend --cov-config=pytest.ini --cov-report=term-missing --cov-report=html

[coverage:run]
omit =
    app/backend/tests/*
    app/backend/__init__.py
