from typing import Protocol, runtime_checkable


@runtime_checkable
class IAnalyticsRepository(Protocol):
    async def get_total_conversations(self, course_filter: list[str] | None = None) -> int: ...
    async def get_active_students(self, course_filter: list[str] | None = None) -> int: ...
    async def get_total_messages(self, course_filter: list[str] | None = None) -> int: ...
    async def get_activity(self, days: int, course_filter: list[str] | None = None) -> list[dict]: ...
    async def get_avg_questions_per_conversation(self, course_filter: list[str] | None = None) -> float: ...
    async def get_course_overview(self, course_id: str) -> dict: ...
    async def get_course_activity(self, course_id: str, days: int) -> list[dict]: ...
    async def get_course_concepts(self, course_id: str) -> list[str]: ...
    async def get_course_sources(self, course_id: str, limit: int = 10) -> list[dict]: ...
