from typing import Protocol, runtime_checkable
from app.backend.schemas.message.models import Message

@runtime_checkable
class ICacheRepository(Protocol):
    async def add_message(self, message: Message) -> None: ...
    async def repopulate_messages(self, conversation_id: str, messages: list[Message]) -> None: ...
    async def get_messages(self, session_id: str) -> list[Message]: ...
    async def set_summary(self, session_id: str, summary: str) -> None: ...
    async def get_summary(self, session_id: str) -> str | None: ...
    async def refresh_session(self, session_id: str) -> None: ...
    async def acquire_summary_lock(self, session_id: str) -> bool: ...
    async def release_summary_lock(self, session_id: str) -> None: ...
    async def set_message_count(self, session_id: str, count: int) -> None: ...
    async def increment_message_count(self, session_id: str) -> int: ...
    async def get_message_count(self, session_id: str) -> int: ...
    async def reset_message_count(self, session_id: str) -> None: ...
    async def trim_messages(self, session_id: str, limit: int = 16) -> None: ...
    async def get_context(self, session_id: str) -> tuple[str | None, list[Message]]: ...
    async def add_token_to_blacklist(self, token: str, expire_in_seconds: int) -> None: ...
    async def is_token_blacklisted(self, token: str) -> bool: ...
