from typing import Protocol, runtime_checkable
from app.backend.schemas.chat.models import Chat

@runtime_checkable
class IChatRepository(Protocol):
    async def create(self, chat: Chat) -> str: ...
    async def get_chat(self, conversation_id: str) -> Chat | None: ...
    async def get_chats(self, user_id: str) -> list[Chat]: ...
    async def get_summary(self, conversation_id: str) -> str | None: ...
    async def set_summary(self, conversation_id: str, summary: str, last_message_id: str) -> None: ...
    async def get_last_summarized_message_id(self, conversation_id: str) -> str | None: ...
    async def touch(self, conversation_id: str) -> None: ...
    async def delete(self, conversation_id: str) -> bool: ...
