from typing import Protocol, runtime_checkable

from app.backend.schemas.course.models import Course

@runtime_checkable
class ICourseRepository(Protocol):
    async def create(self, course: Course) -> str: ...
    async def get_active_courses(self) -> list[Course]: ...
    async def get_all_courses(self) -> list[Course]: ...
    async def get_courses_by_ids(self, ids: list[str]) -> list[Course]: ...
    async def find_by_code(self, code: str) -> Course | None: ...
    async def find_by_id(self, course_id: str) -> Course | None: ...
    async def find_by_name(self, name: str) -> Course | None: ...
    async def update(self, course_id: str, fields: dict) -> bool: ...
    async def delete(self, course_id: str) -> bool: ...
