from typing import Protocol, runtime_checkable

from app.backend.schemas.course.models import Course

@runtime_checkable
class ICourseRepository(Protocol):
    async def create(self, course: Course) -> bool: ...
    async def get_active_courses(self) -> list[Course]: ...
    async def get_courses_by_codes(self, codes: list[str]) -> list[Course]: ...
    async def find_by_code(self, code: str) -> Course | None: ...
    async def find_by_name(self, name: str) -> Course | None: ...
