from typing import Protocol, runtime_checkable
from app.backend.schemas.message.models import Message

@runtime_checkable
class IMessageRepository(Protocol):
    async def create(self, message: Message) -> str: ...
    async def get_message(self, message_id: str) -> Message | None: ...
    async def get_previous_message(self, message_id: str, conversation_id: str) -> Message | None: ...
    async def get_messages(self, conversation_id: str) -> list[Message]: ...
    async def get_recent_messages(self, conversation_id: str, limit: int = 16) -> list[Message]: ...
    async def get_number_of_messages_after_summary(self, conversation_id: str, last_summarized_message_id: str | None) -> int: ...
    async def update_report_status(self, message_id: str, is_reported: bool) -> bool: ...
    async def delete_by_conversation(self, conversation_id: str) -> int: ...
