from typing import Protocol, runtime_checkable
from app.backend.schemas.report.models import Report

@runtime_checkable
class IReportRepository(Protocol):
    async def create(self, report: Report) -> bool: ...
    async def exists_by_message_id(self, message_id: str) -> bool: ...
    async def delete_by_message_id(self, message_id: str) -> bool: ...
    async def delete_by_conversation(self, conversation_id: str) -> int: ...
