from typing import Protocol, runtime_checkable

from app.backend.schemas.memory.models import MemoryType, UserMemory


@runtime_checkable
class IUserMemoryRepository(Protocol):
    async def create(self, memory: UserMemory) -> None: ...
    async def get_by_id(self, memory_id: str) -> UserMemory | None: ...
    async def get_by_key(self, user_id: str, course: str, type: MemoryType, topic: str) -> UserMemory | None: ...
    async def get_by_user_and_course(self, user_id: str, course: str) -> list[UserMemory]: ...
    async def update(self, memory_id: str, fields: dict) -> None: ...
    async def delete(self, memory_id: str) -> None: ...
