from typing import Protocol, runtime_checkable

from app.backend.schemas.user.models import User


@runtime_checkable
class IUserRepository(Protocol):
    async def create(self, user: User) -> bool: ...
    async def find_by_email(self, email: str) -> User | None: ...
    async def find_by_username(self, username: str) -> User | None: ...
    async def find_by_id(self, user_id: str) -> User | None: ...
    async def find_all(self) -> list[User]: ...
    async def update(self, username: str, fields: dict) -> bool: ...
    async def count_with_course(self, course_code: str) -> int: ...
