"""
Shared Data Models.

Defines the core data structures used to pass information safely and
consistently between different components of the RAG pipeline.

Classes:
    RetrievalResults:       Output of ChromaDB query + reranking stage.
    TutorSource:            A single source chunk cited in a tutor response.
    TutorResponse:          Final output of the tutor generation pipeline.
    TutorBenchmarkEntry:    A single entry in a BenchmarkTutor dataset file.
    TutorEvaluationResult:  Scores and metadata for one evaluated tutor response.
"""

from dataclasses import dataclass, field


@dataclass
class IaEduCredentials:
    """
    Per-request IAEdu API credentials supplied by the student's frontend session.

    Attributes:
        url:        IAEdu API endpoint URL.
        channel_id: IAEdu channel identifier.
        api_key:    IAEdu API key.
    """
    url: str
    channel_id: str
    api_key: str


@dataclass
class RetrievalResults:
    """
    Encapsulates the results from a ChromaDB query and subsequent RAG operations.
    Provides a structured, type-safe alternative to nested dictionary unpacking.
    """
    ids: list[str] = field(default_factory=list)
    documents: list[str] = field(default_factory=list)
    metadatas: list[dict[str, object]] = field(default_factory=list)
    distances: list[float] = field(default_factory=list)
    scores: list[float] = field(default_factory=list)

    @classmethod
    def from_chroma_dict(cls, results: dict[str, list]) -> "RetrievalResults":
        """
        Converts the raw ChromaDB output dictionary into a RetrievalResults instance.

        If scores are absent, derives them from cosine distances via `1.0 - distance`.

        Args:
            results: Raw ChromaDB query output with nested lists under 'ids',
                     'documents', 'metadatas', 'distances', and optionally 'scores'.

        Returns:
            A populated RetrievalResults instance.
        """
        ids = results.get("ids", [[]])[0]
        distances = results.get("distances", [[]])[0]

        scores = results.get("scores", [[]])[0]
        if not scores and distances:
            scores = [1.0 - d for d in distances]

        return cls(
            ids=list(ids) if ids else [],
            documents=list(results.get("documents", [[]])[0]),
            metadatas=list(results.get("metadatas", [[]])[0]),
            distances=list(distances) if distances else [],
            scores=list(scores) if scores else [],
        )

    def is_empty(self) -> bool:
        """Returns True if the result set contains no documents."""
        return len(self.ids) == 0


@dataclass
class TutorSource:
    """
    Represents a single source chunk cited in a tutor response.

    Attributes:
        filename: Name of the source document (e.g. 'slides.ED.CAP3.pdf').
        pages:    List of page numbers covered by this chunk.
        score:    Reranker relevance score in [0, 1].
    """
    filename: str
    pages: list[int]

@dataclass
class TutorResponse:
    """
    Final output of the tutor generation pipeline.

    Attributes:
        answer:       The tutor's response text (Socratic guidance or fallback message).
        sources:      List of source chunks used to ground the response.
        is_fallback:  True if no relevant context was found and a fallback message was returned.
        is_guardrail: True if an input guardrail blocked the query before reaching the LLM.
    """
    answer: str
    sources: list[TutorSource]
    is_fallback: bool
    is_guardrail: bool = False
    is_output_guardrail: bool = False


@dataclass
class TutorBenchmarkEntry:
    """
    A single entry in a BenchmarkTutor dataset file.

    Attributes:
        filename:      Source document name (e.g. 'Slides.ED.Aula03.pdf').
        page:          Page number within the source document.
        context:       Raw page text used to generate the question.
        question:      Student question generated from the context.
        question_type: 'regular' (genuine study question) or 'adversarial'
                       (designed to pressure the tutor into bypassing the Socratic method).
    """
    filename: str
    page: str
    context: str
    question: str
    question_type: str
    expected_answer: str = ""


@dataclass
class TutorEvaluationResult:
    """
    Scores and metadata produced by the LLM-as-judge for one tutor response.

    Attributes:
        filename:          Source document name.
        page:              Page number.
        question:          The student's question.
        question_type:     'regular' or 'adversarial'.
        actual_response:   The actual response generated by the tutor pipeline.
        faithfulness:      Score 1-5: response grounded in retrieved context? None if not evaluated.
        non_directiveness: Score 1-5: tutor avoids giving the direct answer? None if not evaluated.
        scaffolding:       Score 1-5: response provides just enough help to move forward? None if not evaluated.
        clarity:           Score 1-5: response is clearly formulated and easy to understand? None if not evaluated.
        semantic_similarity:  Cosine similarity between actual response and expected_answer embeddings (bge-m3).
                              None if not evaluated.
        is_fallback:          True if the retriever found no relevant chunks (real fallback).
        is_guardrail:         True if an input guardrail blocked the query before reaching the LLM.
        is_output_guardrail:  True if the LLM produced a direct answer caught by the output guardrail.
    """
    filename: str
    page: str
    question: str
    question_type: str
    actual_response: str
    faithfulness: int | None
    non_directiveness: int | None
    scaffolding: int | None
    clarity: int | None
    semantic_similarity: float | None
    is_fallback: bool
    is_guardrail: bool
    is_output_guardrail: bool