from typing import Protocol, runtime_checkable, Literal


@runtime_checkable
class IAnalyticsService(Protocol):
    async def resolve_filter_scope(self, payload: dict) -> list[str]: ...

    async def resolve_course_scope(self, course_id: str, payload: dict) -> str: ...

    async def get_overview(self, course_filter: list[str] | None = None) -> dict: ...

    async def get_activity(
        self,
        range_param: Literal["7d", "30d", "90d"],
        course_filter: list[str] | None = None,
    ) -> list[dict]: ...

    async def get_course_overview(self, course_id: str) -> dict: ...

    async def get_course_activity(self, course_id: str, range_param: Literal["7d", "30d", "90d"]) -> list[dict]: ...

    async def get_course_topics(self, course_id: str) -> list[dict]: ...

    async def get_course_sources(self, course_id: str) -> list[dict]: ...
