from typing import Protocol, runtime_checkable
from datetime import timedelta

@runtime_checkable
class ISecurityService(Protocol):
    async def hash_password(self, password: str) -> str: ...
    async def verify_password(self, plain_password: str, hashed_password: str) -> bool: ...
    async def create_access_token(self, data: dict, expires_delta: timedelta | None = None) -> str: ...
    async def decode_token(self, token: str) -> dict: ...
