from typing import Protocol, runtime_checkable
from app.backend.schemas.user.models import User

@runtime_checkable
class IUserService(Protocol):
    async def create_user(
        self, 
        email: str, 
        password: str, 
        full_name: str, 
        role: str, 
        courses: list[str]
    ) -> User: ...
    async def get_user(self, username: str) -> User | None: ...
    async def get_users(self) -> list[User]: ...
    async def update_user(self, username: str, update_data: dict) -> User: ...
    async def delete_user(self, username: str) -> bool: ...
    async def change_password(self, username: str, current_password: str, new_password: str) -> User: ...
